version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis